### ISSUE TITLE
Automatically ignore and/or clean up kernel specifications in notebooks

### ISSUE THREAD

**Issue by jonathansick** [astropy/nbcollection#16]
There was an interesting issue that came up with https://github.com/astropy/astropy-tutorials/pull/504. The issue is that a submitted notebook might have a Jupyter kernel specified that isn't available in the execution environment on GitHub Actions:

```
[nbcollection (ERROR)]: Notebook 'SpectralCubeReprojectExample.ipynb' errored: No such kernel named python39
```

I imagine this'll be fairly common, so we'd want a strategy for accomodating it:

- Automatically strip kernel specifications on contribution to a tutorials repo?
- Have nbcollection automatically ignore the kernel / replace it with one that's available when executing a notebook?

**Comment by adrn** [comment]
Yes, I agree this is important to fix I think the easiest solution would be to strip the kernel specifications for any tutorials in the repo. Can we do that with an [nbstripout](https://github.com/kynan/nbstripout) configuration?

**Comment by jonathansick** [comment]
Right, handling this in the repo itself would solve it.

Adding it as a feature in nbcollection itself would be one less thing for implementors to worry about, on the other hand handling it in the notebook repo gives the implementor more control and the notebooks themselves, if downloaded by others, would already be in a "clean/normalized" state.
