### ISSUE TITLE
readthedocs.org Documentation

### ISSUE THREAD

**Issue by jbcurtin** [astropy/nbcollection#3]
Any objection on implementing readthedocs.org documentation?

Rendering the docs locally can be accomplished with,
https://github.com/jbcurtin/cloud-fits/blob/master/build.sh#L5

**Comment by adrn** [comment]
Just to clarify, do you mean writing some documentation for users that want to use `nbcollection`, and deploying it with RTD?

**Comment by jbcurtin** [comment]
ah yeah, that is exactly it

**Comment by jbcurtin** [comment]
This seems to have been setup. Closing the issue.
